# conditioning and reco columns for jets

jet_cond = [
    "MClosestMuon_dr",
    "MClosestMuon_pt",
    "MClosestMuon_deta",
    "MClosestMuon_dphi",
    "MSecondClosestMuon_dr",
    "MSecondClosestMuon_pt",
    "MSecondClosestMuon_deta",
    "MSecondClosestMuon_dphi",
    "MGenJet_eta",
    "MGenJet_mass",
    "MGenJet_phi",
    "MGenJet_pt",
    "MGenJet_EncodedPartonFlavour_light",
    "MGenJet_EncodedPartonFlavour_gluon",
    "MGenJet_EncodedPartonFlavour_c",
    "MGenJet_EncodedPartonFlavour_b",
    "MGenJet_EncodedPartonFlavour_undefined",
    "MGenJet_EncodedHadronFlavour_b",
    "MGenJet_EncodedHadronFlavour_c",
    "MGenJet_EncodedHadronFlavour_light",
]

jet_names = [
    "area",
    "bRegCorr",
    "bRegRes",
    "btagCSVV2",
    "btagDeepB",
    "btagDeepCvB",
    "btagDeepCvL",
    "btagDeepFlavB",
    "btagDeepFlavCvB",
    "btagDeepFlavCvL",
    "btagDeepFlavQG",
    "cRegCorr",
    "cRegRes",
    "chEmEF",
    "chFPV0EF",
    "chHEF",
    "cleanmask",
    "etaMinusGen",
    "hadronFlavour",
    "hfadjacentEtaStripsSize",
    "hfcentralEtaStripSize",
    "hfsigmaEtaEta",
    "hfsigmaPhiPhi",
    "jetId",
    "massRatio",
    "muEF",
    "muonSubtrFactor",
    "nConstituents",
    "nElectrons",
    "nMuons",
    "neEmEF",
    "neHEF",
    "partonFlavour",
    "phiMinusGen",
    "ptRatio",
    "puId",
    "puIdDisc",
    "qgl",
    "rawFactor",
]

reco_columns = [f"MJet_{name}" for name in jet_names]
